# Generated by Django 3.2.9 on 2021-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mywallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mywallet',
            name='enabled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
