# Generated by Django 3.2.9 on 2021-11-09 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211108_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(null=True)),
                ('refernce_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('user_id', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
