# Generated by Django 3.2.9 on 2021-11-09 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_refernce_id_wallettransactions_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
