# Generated by Django 3.2.9 on 2021-11-10 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wallettransactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='reference_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100),
        ),
    ]
